"""Project-wide constants."""

from typing import List

# Classification horizons default values
DEFAULT_CLASSIFICATION_HORIZONS: List[int] = [3, 5, 10]

# Label mode
DEFAULT_LABEL_MODE: str = "threshold"

# Per-horizon classification thresholds（短周期用小阈值，长周期用大阈值）
DEFAULT_CLASSIFICATION_THRESHOLD_3D: float = 0.01
DEFAULT_CLASSIFICATION_THRESHOLD_5D: float = 0.015
DEFAULT_CLASSIFICATION_THRESHOLD_10D: float = 0.02

# LSTM default hyperparameters
DEFAULT_LSTM_HIDDEN_SIZE: int = 64
DEFAULT_LSTM_NUM_LAYERS: int = 2
DEFAULT_LSTM_DROPOUT: float = 0.2
DEFAULT_LSTM_EPOCHS: int = 50
DEFAULT_LSTM_BATCH_SIZE: int = 256
DEFAULT_LSTM_LEARNING_RATE: float = 0.001
DEFAULT_LSTM_SEQUENCE_LENGTH: int = 60
DEFAULT_LSTM_NORMALIZATION_WINDOW: int = 300

# XGBoost default hyperparameters
DEFAULT_XGB_N_ESTIMATORS: int = 100
DEFAULT_XGB_MAX_DEPTH: int = 6
DEFAULT_XGB_LEARNING_RATE: float = 0.1
DEFAULT_XGB_MIN_CHILD_WEIGHT: int = 1
DEFAULT_XGB_SUBSAMPLE: float = 1.0
DEFAULT_XGB_COLSAMPLE_BYTREE: float = 1.0

# LSTM training hyperparameters
DEFAULT_LSTM_WEIGHT_DECAY: float = 0.001
DEFAULT_LR_SCHEDULER_FACTOR: float = 0.5
DEFAULT_LR_SCHEDULER_PATIENCE: int = 3
DEFAULT_VAL_SIZE: float = 0.2

# Training defaults
DEFAULT_LABEL_SMOOTHING: float = 0.1
DEFAULT_EARLY_STOPPING_PATIENCE: int = 10
