"""Project-wide constants."""

from typing import List

# Classification horizons default values
DEFAULT_CLASSIFICATION_HORIZONS: List[int] = [3, 5, 10]
DEFAULT_CLASSIFICATION_THRESHOLD: float = 0.02

# LSTM default hyperparameters
DEFAULT_LSTM_HIDDEN_SIZE: int = 64
DEFAULT_LSTM_NUM_LAYERS: int = 2
DEFAULT_LSTM_DROPOUT: float = 0.2
DEFAULT_LSTM_EPOCHS: int = 50
DEFAULT_LSTM_BATCH_SIZE: int = 256
DEFAULT_LSTM_LEARNING_RATE: float = 0.001
DEFAULT_LSTM_SEQUENCE_LENGTH: int = 60
DEFAULT_LSTM_NORMALIZATION_WINDOW: int = 300

# XGBoost default hyperparameters
DEFAULT_XGB_N_ESTIMATORS: int = 100
DEFAULT_XGB_MAX_DEPTH: int = 6
DEFAULT_XGB_LEARNING_RATE: float = 0.1
DEFAULT_XGB_MIN_CHILD_WEIGHT: int = 1
DEFAULT_XGB_SUBSAMPLE: float = 1.0
DEFAULT_XGB_COLSAMPLE_BYTREE: float = 1.0

# Training defaults
DEFAULT_LABEL_SMOOTHING: float = 0.1
DEFAULT_EARLY_STOPPING_PATIENCE: int = 10
