"""SignalGenerator module for execution pipeline."""

from typing import List, Dict
from trade_alpha.execution.schemas import StockSignal
from trade_alpha.strategy.service import get_strategy_instance


class SignalGenerator:
    """Signal generator for generating trading signals based on predictions."""

    def __init__(self, strategy_id: str):
        """
        Initialize SignalGenerator.

        Args:
            strategy_id: Strategy configuration ID
        """
        self.strategy_id = strategy_id
        self.strategy_service = None

    async def generate_signals(
        self,
        predictions: List[Dict],
        current_data: Dict,
    ) -> List[StockSignal]:
        """
        Generate trading signals based on predictions and current data.

        Args:
            predictions: List of prediction dictionaries containing ts_code and predicted values
            current_data: Dictionary containing current market data keyed by ts_code

        Returns:
            List of StockSignal objects
        """
        signals = []
        strategy = await get_strategy_instance(self.strategy_id)

        for prediction in predictions:
            ts_code = prediction.get("ts_code")
            if not ts_code:
                continue

            current_price = current_data.get(ts_code, {}).get("close", 0.0)
            
            from trade_alpha.strategy.base import StrategyContext
            
            context = StrategyContext(
                ts_code=ts_code,
                trade_date=prediction.get("trade_date", ""),
                current_price=float(current_price),
                prediction=prediction.get("prediction", {}),
                indicators=prediction.get("indicators", {}),
            )

            action = strategy.decide(context)
            signal_strength = self._calculate_signal_strength(prediction)

            signal = StockSignal(
                ts_code=ts_code,
                action=action,
                signal_strength=signal_strength,
                current_price=float(current_price),
                prediction=prediction.get("prediction", {}),
                reason=f"Signal generated by strategy {self.strategy_id}",
            )
            signals.append(signal)

        return signals

    def _calculate_signal_strength(self, prediction: Dict) -> float:
        """
        Calculate signal strength based on prediction confidence.

        Args:
            prediction: Prediction dictionary

        Returns:
            Signal strength between 0 and 1
        """
        confidence = prediction.get("confidence", 0.5)
        return min(max(float(confidence), 0.0), 1.0)